### ISSUE TITLE
Scripts in config folder

### ISSUE THREAD

**Issue by ivanocerrato** [netgroup-polito/frog4-openstack-do#12]
The config folders contains two python scripts:
* https://github.com/netgroup-polito/frog4-openstack-do/blob/master/config/deletegraph.py
* https://github.com/netgroup-polito/frog4-openstack-do/blob/master/config/putgraph.py

The config folder should only contain **configuration** files; scripts should be put in the [scripts](https://github.com/netgroup-polito/frog4-openstack-do/tree/master/scripts) folder.

**Comment by frisso** [comment]
Add a little text in the script explaining what it does.

**Comment by ReliableLion** [comment]
Description added.

**Comment by ivanocerrato** [comment]
I have improved a little bit the scripts to create and delete a graph.
