### ISSUE TITLE
Configuration file

### ISSUE THREAD

**Issue by ivanocerrato** [netgroup-polito/frog4-openstack-do#13]
In this portion of the configuration file https://github.com/netgroup-polito/frog4-openstack-do/blob/master/config/default-config.ini#L33-L42, 
there are two sections [jolnet] and [networks], both with a single parameter.

Since both the sections are related to the jolnet, I propose to create a single section as follows:

[jolnet]
jolnet_mode=true
jolnet_networks=...

**Comment by ReliableLion** [comment]
The config.py file which retrieves those informations has been updated and so the default-config.ini file. I think this choice makes sense.
