### ISSUE TITLE
debug mode

### ISSUE THREAD

**Issue by ivanocerrato** [netgroup-polito/frog4-openstack-do#14]
Why do we have two "debug" fields in the configuration file ?

* debug_mode https://github.com/netgroup-polito/frog4-openstack-do/blob/master/config/default-config.ini#L28
* debug https://github.com/netgroup-polito/frog4-openstack-do/blob/master/config/default-config.ini#L80

There exist any difference? Can we use some more meaningful name?

**Comment by ReliableLion** [comment]
The debug_mode enables debugging mode. The debug option specify the log level. I changed the second one, and updated the relative config.py, in a more meaningful name: debug_level

**Comment by ivanocerrato** [comment]
Now we have:
* debug_mode
* debug_level
I think that the two terms are not clean yet. 

I would call this https://github.com/netgroup-polito/frog4-openstack-do/blob/master/config/default-config.ini#L28 "fake_running", while I would call the second "debug_mode".

**Comment by ReliableLion** [comment]
Yes it would be better, even if the second should specify the log level. Maybe a single option it's better:
Now:
   - debug_level
   - verbose_level
Then:
   - log_level: debug/verbose

**Comment by ivanocerrato** [comment]
I don't understand your proposal

**Comment by ivanocerrato** [comment]
Yesterday we noted that this field https://github.com/netgroup-polito/frog4-openstack-do/blob/master/config/default-config.ini#L26-L28 does not have any effect when set to `true`. Then I propose to remove it from the configuration file, and then to delete its usage from the code.

@rbrtbnfgl  or @ReliableLion , can one of you take care of this issue?

**Comment by rbrtbnfgl** [comment]
If it is enabled it increase the information stored on a file and will always returned true only when the graph status is requested.

**Comment by ivanocerrato** [comment]
Well, then please remove it. Imho it is completely useless.

**Comment by ReliableLion** [comment]
I used the field also to write the flows in a file for debugging. Beyond that, that field was used as Roberto said. So I could remove it.

**Comment by ivanocerrato** [comment]
If also @rbrtbnfgl  agrees, you can remove that flag.

To me, the code to print flows on files in very useful. You can enable it in case this flag here https://github.com/netgroup-polito/frog4-openstack-do/blob/master/config/default-config.ini#L80 is `verbose` (i then agree with your previous suggestion).

**Comment by ReliableLion** [comment]
Ok, so I'll remove the debug_mode field and then leave only a "log_level". The latter if is set to verbose will print the flows in a file, is that right?

**Comment by ivanocerrato** [comment]
The latter will do what it is already doing now + it will print the flows in a file.

@rbrtbnfgl  do you agree?

**Comment by ivanocerrato** [comment]
@ReliableLion please proceed. Roberto just told me that he agrees.

**Comment by ReliableLion** [comment]
Ok I deleted the debug_mode field and used the debug_level field to print the flows in a file.

**Comment by ivanocerrato** [comment]
Just a detail: can you replace `debug_level` with `debug_mode`?

**Comment by ReliableLion** [comment]
Yes Done.

**Comment by ivanocerrato** [comment]
Then I close the issue.
