### ISSUE TITLE
Error in parsing information associated with DD

### ISSUE THREAD

**Issue by ivanocerrato** [netgroup-polito/frog4-openstack-do#15]
There is the following bug when parsing the INI file, which requires that this line https://github.com/netgroup-polito/frog4-openstack-do/blob/master/config/default-config.ini#L66 is set to the same value of line https://github.com/netgroup-polito/frog4-openstack-do/blob/master/config/default-config.ini#L68 .

This must be fixed asap.

**Comment by rbrtbnfgl** [comment]
https://github.com/netgroup-polito/frog4-openstack-do/commit/f3b022252cbd922c8c9f95e993db95a7d7fd4813
Corrects the error
