### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by ivanocerrato** [netgroup-polito/frog4-openstack-do#17]
Here https://github.com/netgroup-polito/frog4-openstack-do#rest-api it says that the API is documented at {Domain_Orchestrator_Address}/apidocs/index.html. 
It seems that this page does not work properly.

**Comment by farmanullahcs** [comment]
Fixed in the branch [frog4-deployment](https://github.com/netgroup-polito/frog4-openstack-do/tree/frog4-deployment)
