### ISSUE TITLE
The OS-DO does not use the functional capabilities to select the VNF

### ISSUE THREAD

**Issue by ivanocerrato** [netgroup-polito/frog4-openstack-do#18]
The OS-DO wants that the NF-FG contains the `vnf_template` field, which points to a valid template into the datastore. This is due to a bug in the NFFG library, which sets this parameter as mandatory https://github.com/netgroup-polito/nffg-library/blob/master/schema.json#L320 .
I have added a specific issue also here https://github.com/netgroup-polito/nffg-library/issues/2

Moreover, the OS-DO completely ignores the "functional-capability" field.

**Comment by rbrtbnfgl** [comment]
Done in https://github.com/netgroup-polito/frog4-openstack-do/commit/1e089c4fd266903e0d10d5e892b7fc33caf22565
Waiting the update of the orchestrator for the field vnf-template mandatory.
After that it should be merged with the master.

**Comment by rbrtbnfgl** [comment]
Merged with master
