### ISSUE TITLE
The Domain Information Library must be used to handle the domain description file

### ISSUE THREAD

**Issue by ivanocerrato** [netgroup-polito/frog4-openstack-do#19]
This library is available here https://github.com/netgroup-polito/domain-information-library .

**Comment by ivanocerrato** [comment]
There is an issue similar here https://github.com/netgroup-polito/frog4-openstack-do/issues/1. For now, I will keep both of them since, if I understand correctly, they are a little bit different.

**Comment by rbrtbnfgl** [comment]
done in https://github.com/netgroup-polito/frog4-openstack-do/commit/1e089c4fd266903e0d10d5e892b7fc33caf22565
