### ISSUE TITLE
Folder cleanup

### ISSUE THREAD

**Issue by ivanocerrato** [netgroup-polito/frog4-openstack-do#20]
What are all the .json files in this folder https://github.com/netgroup-polito/frog4-openstack-do/tree/master/config ? Do we actually need all of them.

Please, delete those that are useless.

**Comment by ReliableLion** [comment]
All the files should be useful. They describe some configuration files used in some readme. Maybe firstgraph and secondgraph could be deleted because they were there as an example of VNF-VNF FG and Endpoint-VNF FG.

**Comment by ivanocerrato** [comment]
Then I propose to add a README.md in that folder, which explains what each file contains.
For instance, if each file includes a different example, the README.md should explain which peculiarity is shown in each file (since all pf them are needed, I guess that each of them shows something different).

**Comment by ivanocerrato** [comment]
You may do something similar to what I have done for the resource description https://github.com/netgroup-polito/frog4-openstack-do/tree/master/config/ResourceDescriptions

**Comment by ReliableLion** [comment]
I added the readme to the config folder.

**Comment by ivanocerrato** [comment]
*The openstacknode.json file is an example of the SONA configuration file pointed in this guide. In this example the file describes a domain made up of two compute nodes. This file can be generated using this script* 

Then, why is it important to keep this file here, if it is generated automatically?

----------------------------

*The ovsdbrest.json file is an example of configuration requested by the Ovsdb-rest app. More information can be found here.*

Since this is a configuration file for an application that is into another repository, why this file is not in that repository? What is the purpose of keeping it here?

**Comment by ReliableLion** [comment]
The first file could be eliminated, it's just an example to show the kind of configuration that SONA accept.
The second one I agree to delete it. It's already in the repository of the ovsdb-rest apps, which is linked also in the guide. So I proceed to delete the second file.
What about the first one? I'll keep it there or do I delete anyway?

**Comment by ivanocerrato** [comment]
Ok for deleting the second file.

About the first, is it explained somewhere how to configure SONA?

**Comment by ReliableLion** [comment]
Yes in this guide https://github.com/netgroup-polito/frog4-openstack-do/blob/master/README_ONOS.md within SONA configuration section.

**Comment by ivanocerrato** [comment]
Then I propose to keep the json file in that folder, and add a reference to this file inside README_ONOS.md

**Comment by ReliableLion** [comment]
Yes the reference is already in the guide.

**Comment by ivanocerrato** [comment]
Ok, then I close the issue.
