### ISSUE TITLE
Availability zone

### ISSUE THREAD

**Issue by frisso** [netgroup-polito/frog4-openstack-do#22]
@rbrtbnfgl: is the "availability zone" compulsory in this DO? Can we leave it blank? Please update the config.ini with this info.

**Comment by rbrtbnfgl** [comment]
Done in https://github.com/netgroup-polito/frog4-openstack-do/commit/e57609009d33aaee31f7463ebb04cc1d9ae16b4f

**Comment by frisso** [comment]
@rbrtbnfgl Could you please updated also the config.ini? Can we leave it blank, it is an optional field, or what?

**Comment by rbrtbnfgl** [comment]
Not blank if the parameter is not given on the configuration file Nova will select the availability zone by itself.

**Comment by frisso** [comment]
Adding a better comment with commit 758899a.
Closing the issue.
