### ISSUE TITLE
Useless code in the frog4-openstack-do

### ISSUE THREAD

**Issue by farmanullahcs** [netgroup-polito/frog4-openstack-do#24]
The frog4-openstack-do has some code that is useless, Can i remove this code?
1) [code 1](https://github.com/netgroup-polito/frog4-openstack-do/blob/master/do_core/exception.py#L19-#L64)
2) [code 2](https://github.com/netgroup-polito/frog4-openstack-do/blob/master/do_core/exception.py#L94-#L128)
3) [code 3](https://github.com/netgroup-polito/frog4-openstack-do/blob/master/do_core/exception.py#L139-#L155)
4) [code 4](https://github.com/netgroup-polito/frog4-openstack-do/blob/master/do_core/exception.py#L76-#L83)
5) [code 5](https://github.com/netgroup-polito/frog4-openstack-do/blob/master/do_core/exception.py#L184-#L227)
6) [code 6](https://github.com/netgroup-polito/frog4-openstack-do/blob/master/do_core/exception.py#L256-#L263)
7) [code 7](https://github.com/netgroup-polito/frog4-openstack-do/blob/master/do_core/ovsdb.py#L44-#L50)
8) [code 8](https://github.com/netgroup-polito/frog4-openstack-do/blob/master/do_core/ovsdb.py#L64-#L77)
9) [code 9](https://github.com/netgroup-polito/frog4-openstack-do/blob/master/do_core/sql/session.py#L54-#L80)
10) [code 10](https://github.com/netgroup-polito/frog4-openstack-do/blob/master/do_core/sql/session.py#L100-#L107)
11) [code 11](https://github.com/netgroup-polito/frog4-openstack-do/blob/master/do_core/sql/session.py#L118-#L140)
12) [code 12](https://github.com/netgroup-polito/frog4-openstack-do/blob/master/do_core/sql/session.py#L152-#L158)
13) [code 13](https://github.com/netgroup-polito/frog4-openstack-do/blob/master/do_core/sql/session.py#L164-#L186)

**Comment by frisso** [comment]
Please proceed.

**Comment by farmanullahcs** [comment]
Useless code removed in the branch, [frog4-deployment](https://github.com/netgroup-polito/frog4-openstack-do/tree/frog4-deployment)
