### ISSUE TITLE
Update OpenStack documentation

### ISSUE THREAD

**Issue by ivanocerrato** [netgroup-polito/frog4-openstack-do#8]
[README_OPENSTACK.md](https://github.com/netgroup-polito/frog4-openstack-do/blob/master/README_OPENSTACK.md) only describes how to configure OpenStack with ONOS.
In fact, all the things to do that are related with ONOS are written in another file.

Please, in README_OPENSTACK.md write that it is possible to install OS both with ONOS and ODL, and that, while instructions about ODL are in the current file, ONOS is instead described into another file (put then the pointer).

**Comment by ivanocerrato** [comment]
@ReliableLion, I think that this issue has not been addressed yet,

**Comment by ReliableLion** [comment]
The guide is updated. Check the last commit in case it's still missing some information.
