### ISSUE TITLE
Improve documentation about ovsdb-rest

### ISSUE THREAD

**Issue by ivanocerrato** [netgroup-polito/frog4-openstack-do#9]
This section https://github.com/netgroup-polito/frog4-openstack-do/blob/master/README_INSTALL.md#onos-support is not clear.

For instance, what does it mean "Remember to update the ovsdb-rest configuration based on your topology (usually an ovsdb node for each compute node)".
Please, write the commands to be used to this purpose.

**Comment by ReliableLion** [comment]
The guide should be clear now. Let me know if not.
